services:
  photoapp:
    image: 555cijaiz555/reactphoto:v11
    container_name: reactphotoappv11
    ports:
      - "3001:3001"
    volumes:
      - /home/ubuntu/photoapp/uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - PORT=3001
    restart: unless-stopped
    networks:
      - photonet

networks:
  photonet:
    driver: bridge

volumes:
  uploads:
    driver: local