services:
  backend:
    image: 555cijaiz555/rback:v4
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000"   # expose internally, not mapped to host
    environment:
      - DB_SERVER=gnanabi.database.windows.net
      - DB_PORT=1433
      - DB_DATABASE=mansion
      - DB_USER=servergnanaabi
      - DB_PASSWORD=serverpassword@123
      - EXPRESS_PORT=5000
      - NODE_ENV=production
    deploy:
      replicas: 3   # Run 3 containers for the API service
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.2"      # Max 50% of a CPU per container
          memory: 125M     # Max 512 MB RAM per container
        reservations:
          cpus: "0.1"     # Reserve 25% of a CPU
          memory: 64M     # Reserve 256 MB RAM
    networks:
      - mansion-network
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:90"   # host:container mapping
    volumes:
      - /home/ubuntu/config/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"      # Max 50% of a CPU per container
          memory: 64M     # Max 512 MB RAM per container
        reservations:
          cpus: "0.1"     # Reserve 25% of a CPU
          memory: 32M     # Reserve 256 MB RAM
    networks:
      - mansion-network

  frontend:
    image: 555cijaiz555/rfront:v4
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://68.233.119.219/api
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://68.233.119.219/api
    deploy:
      resources:
        limits:
          cpus: "0.1"      # Max 50% of a CPU per container
          memory: 125M     # Max 512 MB RAM per container
    networks:
      - mansion-network
    restart: unless-stopped

  # Frontend application
  client:
    image: 555cijaiz555/ecomc:v2
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://68.233.119.219/api}
      - PORT=3002
    expose:
      - 3002
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 125M
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - mansion-network
    restart: on-failure

  # Backend API server
  server:
    image: 555cijaiz555/ecoms:v2
    environment:
      - NODE_ENV=production
      - PORT=5002
      - CLIENT_URL=http://140.245.238.26
      - DB_SERVER=${DB_SERVER:-gnanabi.database.windows.net}
      - DB_NAME=${DB_NAME:-ecommerce}
      - DB_USER=${DB_USER:-servergnanaabi}
      - DB_PASSWORD=${DB_PASSWORD:-serverpassword@123}
      - DB_PORT=${DB_PORT:-1433}
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - "5002"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 124M
    networks:
      - mansion-network
    restart: on-failure

networks:
  mansion-network:
    driver: bridge

volumes:
  server-uploads:
    driver: local