services:
  # Nginx reverse proxy (main entry point)
  # nginx:
  #   image: 555cijaiz555/nginx:v1
  #   container_name: ecommerce-nginx
  #   ports:
  #     - "90:80"
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.1'
  #         memory: 32M
  #   depends_on:
  #     - client
  #     - server
  #   networks:
  #     - ecommerce-network
  #   restart: on-failure
  #   healthcheck:
  #     test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://140.245.238.26/health"]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 3
  #     start_period: 10s

  # Frontend application
  client:
    image: 555cijaiz555/ecomc:v2
    container_name: ecommerce-client
    ports:
      - "3002:3002"
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL:-http://140.245.238.26/api}
      - PORT=3002
    expose:
      - 3002
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 124M
    depends_on:
      - server
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./app.conf:/etc/nginx/conf.d/app.conf
    networks:
      - ecommerce-network
    restart: on-failure

  # Backend API server
  server:
    image: 555cijaiz555/ecoms:v2
    container_name: ecommerce-server
    environment:
      - NODE_ENV=production
      - PORT=5002
      - CLIENT_URL=http://140.245.238.26
      - DB_SERVER=${DB_SERVER:-gnanabi.database.windows.net}
      - DB_NAME=${DB_NAME:-ecommerce}
      - DB_USER=${DB_USER:-servergnanaabi}
      - DB_PASSWORD=${DB_PASSWORD:-serverpassword@123}
      - DB_PORT=${DB_PORT:-1433}
    volumes:
      - ./server/uploads:/app/uploads
    ports:
      - "5002:5002"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 124M
    networks:
      - ecommerce-network
    restart: on-failure
networks:
  ecommerce-network:
    driver: bridge

volumes:
  server-uploads:
    driver: local